security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
              pattern:  ^/(_(profiler|wdt)|css|images|js)/
              security: false

        public:
              # since anonymous is allowed users will not be forced to login
              pattern:   ^/.*
              form_login:
                  login_path: fos_user_security_login
                  check_path: fos_user_security_check
                  provider: fos_userbundle
                  default_target_path:  /
                  remember_me: true
              remember_me:
                  always_remember_me: true
                  key:         %secret%
                  lifetime: 31536000
                  path:     /
                  domain:   ~
                  user_provider: fos_userbundle
              anonymous: true
              logout: true

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/email/statistic, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
