<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReferencementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferencementRepository extends EntityRepository
{
    public function getSelectlist()
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r.region')
            ->distinct('r.region')
            ->getQuery();

        return $qb->getResult();
    }

    public function getPrestation($prestations)
    {
        $query = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.rub =:rub')
                ->setParameter('rub', $prestations);
        return $query->getQuery()->getResult();

    }
}
