parameters:
#    utilisateurs.example.class: Utilisateurs\UtilisateursBundle\Example


services:
#    utilisateurs.example:
#        class: %utilisateurs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

# services:
#     twig.extension.date:
#        class: Twig_Extensions_Extension_Date
#        tags:
#             - { name: twig.extension }

services:
    activity_listener:
        class: Utilisateurs\UtilisateursBundle\Listener\ActivityListener
        arguments: [@security.context, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }